version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - PROJECT_ROOT=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload

  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    command: python grpc_main.py

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_HOST=fastapi
      - API_PORT=8005
    command: streamlit run src/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
  
  mlflow:
    image: mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: ["server", "/data"]

